# Load the RatOS moonraker defaults
[include RatOS/moonraker.conf]

# If you use a non standard ip range in your local network, 
# you can specify it under trusted_clients here.
[authorization]
cors_domains:
    http://*.local
trusted_clients:
    127.0.0.1
    192.168.0.0/16
    192.168.100.0/24
    FE80::/10
    ::1/128
    FD00::/8

#[power Enclosure Led]
#type = shelly
#address = 192.168.100.78

#[power SKRat Power]
#type = shelly
#address = 192.168.100.76

[spoolman]
server = http://192.168.100.236:7912/
sync_rate = 5

[timelapse]

#[wled DaybreakNeo]
#type: http
#address: 192.168.1.131 #ip address of your Rainbowshift ESP8266
#initial_red: 0.2
#initial_green: 0.2
#initial_blue: 0.2
#chain_count: 26 #the number of individual LEDs connected to RainbowShift

